### ISSUE TITLE
Router-perf should support clusters with no workload node

### ISSUE THREAD

**Issue by chaitanyaenr** [cloud-bulldozer/e2e-benchmarking#131]
Clusters might not have the workload node, for example the cluster used by the e2e CI. We need to expose the parameters which enables/disables running the test orchestrator from the workload node:

export WORKLOAD_JOB_NODE_SELECTOR=<true/false>
export WORKLOAD_JOB_TAINT=<true/false>

Also, looks like it's running the comparison even COMPARE is set to false, https://github.com/cloud-bulldozer/e2e-benchmarking/blob/40fd02e31fcde573be70e26405a89e85232ad69a/workloads/router-perf/run_router_test.sh#L82 needs to run only COMPARE=true.

**Comment by chaitanyaenr** [comment]
cc: @Harshith-umesh @mohit-sheth

**Comment by mohit-sheth** [comment]
resolved
