### ISSUE TITLE
Upgrade-perf workload should support upgrading to nightly builds

### ISSUE THREAD

**Issue by chaitanyaenr** [cloud-bulldozer/e2e-benchmarking#138]
OpenShift cluster upgrades uses channel defined in cincinnati - https://github.com/openshift/cincinnati-graph-data/tree/master/channels to determine if there are any upgrades available. It's set to stable-4.x or candiate-4.x and both of them doesn't track the nightly OCP builds since they are not GA.

**Comment by mohit-sheth** [comment]
resolved
