### ISSUE TITLE
Running in OpenShift Pod based Jenkins Agent

### ISSUE THREAD

**Issue by kedark3** [cloud-bulldozer/e2e-benchmarking#163]
Hi @rsevilla87  in my team we are planning to run these in the jenkins agent that runs as a pod on OpenShift. I have not previously tried to run docker/podman within an openshift pod. Do you happen to know a way to do so? 
I believe this script was designed by keeping in mind that it would be ran from a jump host machine in the scale lab and not a container/pod. 

https://github.com/cloud-bulldozer/e2e-benchmarking/blob/af7eb1db8089d4a6507087810097648e4d3f36a5/workloads/router-perf-v2/common.sh#L54

Alternatively, I was thinking using kube-burner binary directly within the jenkins agent pod. Would you be able to accept that as a proposed change if that works for us. 

Thanks.

**Comment by rsevilla87** [comment]
Fixed in #164
