### ISSUE TITLE
Add new baremetal workloads

### ISSUE THREAD

**Issue by mukrishn** [cloud-bulldozer/e2e-benchmarking#223]
Create new scripts for running benchmark-operator workloads on baremetal cluster. 
- trex/tespmd
- oslat
- cyclictest

The trex & testpmd workload needs [SR-IOV](https://github.com/cloud-bulldozer/benchmark-operator/blob/master/docs/testpmd.md#sample-sr-iov-configuration), [PAO](https://github.com/cloud-bulldozer/benchmark-operator/blob/master/docs/testpmd.md#sample-pao-configuration) operators and BIOS configuration, ensure it is included before running the actual workload.

**Comment by mkarg75** [comment]
oslat isn't really working out of the benchmark operator, working with @rsevilla on getting that fixed. trex / testpmd worked for me except for the fact that the testpmd pod never "completes". will need to look into that.

**Comment by jtaleric** [comment]
@mkarg75 do we have a bug on oslat?

**Comment by mkarg75** [comment]
@jtaleric Raul fixed the issue. Let's see if there are more.

**Comment by mukrishn** [comment]
Done - https://github.com/cloud-bulldozer/e2e-benchmarking/pull/264
