### ISSUE TITLE
Configmap unable to get created due to number not string

### ISSUE THREAD

**Issue by paigerube14** [cloud-bulldozer/e2e-benchmarking#231]
Sometimes when large amounts of iterations of the cluster-density test are run, the {{rand 4}} or {{rand 10}} produce a number and the configmap is not able to get created properly. See output below

09-02 01:18:39.880  time="2021-09-02 05:18:39" level=error msg="Error creating object: ConfigMap in version \"v1\" cannot be handled as a ConfigMap: v1.ConfigMap.Data: ReadString: expects \" or n, but found 9, error found in #10 byte of ...|:{\"key1\":9764,\"key2\"|..., bigger context ...|{\"apiVersion\":\"v1\",\"data\":{\"key1\":9764,\"key2\":\"sQxmxGVmZV\"},\"kind\":\"ConfigMap\",\"metad|..."
09-02 01:18:39.880  time="2021-09-02 05:18:39" level=error msg="Retrying object creation"
09-02 01:18:40.529  time="2021-09-02 05:18:40" level=error msg="Error creating object: ConfigMap in version \"v1\" cannot be handled as a ConfigMap: v1.ConfigMap.Data: ReadString: expects \" or n, but found 9, error found in #10 byte of ...|:{\"key1\":9764,\"key2\"|..., bigger context ...|{\"apiVersion\":\"v1\",\"data\":{\"key1\":9764,\"key2\":\"sQxmxGVmZV\"},\"kind\":\"ConfigMap\",\"metad|..."
09-02 01:18:40.529  time="2021-09-02 05:18:40" level=error msg="Retrying object creation"
09-02 01:18:43.869  time="2021-09-02 05:18:43" level=error msg="Error creating object: ConfigMap in version \"v1\" cannot be handled as a ConfigMap: v1.ConfigMap.Data: ReadString: expects \" or n, but found 9, error found in #10 byte of ...|:{\"key1\":9764,\"key2\"|..., bigger context ...|{\"apiVersion\":\"v1\",\"data\":{\"key1\":9764,\"key2\":\"sQxmxGVmZV\"},\"kind\":\"ConfigMap\",\"metad|..."

I think a quick fix for this is to add quotes around "{{rand 4}}" so in case it isn't a string it'll be passed as one and the config will be able to 

Testing out a fix in: https://github.com/paigerube14/e2e-benchmarking/tree/quotes

**Comment by mohit-sheth** [comment]
fixed
