### ISSUE TITLE
router-perf-v2 failed because to the endpoints can not be reached

### ISSUE THREAD

**Issue by qiliRedHat** [cloud-bulldozer/e2e-benchmarking#298]
router-perf-v2 failed because to the endpoints can not be reached.
```
Mon Dec 13 09:28:58 AM UTC 2021 Testing all routes before triggering the workload
curl: (52) Empty reply from server
```
Manually access the endpoints also failed.
```
% oc get route -n http-scale-http --no-headers -o custom-columns="route:.spec.host" | grep 499                    
http-perf-499-http-scale-http.apps.qili-aws-ovn.qe.devcluster.openshift.com

% oc get pod -n http-scale-http | grep 499        
http-perf-499   1/1     Running   0          57m

% curl --retry 3 --connect-timeout 5 -sSk http://http-perf-499-http-scale-http.apps.qili-aws-ovn.qe.devcluster.openshift.com
curl: (52) Empty reply from server
```

**Comment by sjug** [comment]
Hi @qiliRedHat,

Having unreachable endpoints seems like there is a network issue in your cluster as that curl step is essentially a pre-launch flight check. Is your cluster healthy? Do you have the full run log of the test you could share?

**Comment by qiliRedHat** [comment]
@sjug Here is the full log:
[router-perf-v2.log](https://github.com/cloud-bulldozer/e2e-benchmarking/files/7707907/router-perf-v2.log)

**Comment by qiliRedHat** [comment]
I tried again and it works, so this should be my cluster's problem. Sorry and close.
