### ISSUE TITLE
[Idea] Print log when a benchmark fails to ease debugging

### ISSUE THREAD

**Issue by rsevilla87** [cloud-bulldozer/e2e-benchmarking#305]
I think we could print some of the workload logs (Not the benchmark operator ones, but from the actual pods of the workload) and when a benchmark fails. We're currently blind when that happens and sometimes implies re-running it manually, hence waste of time.

A right place to add this feature could be within the run_benchmark function:
https://github.com/cloud-bulldozer/e2e-benchmarking/blob/fc86aa51d67723e9dee48fe06da4b8eeeaa81a9f/utils/benchmark-operator.sh#L53-L59

**Comment by dry923** [comment]
Can we just dump all the logs to snappy when it fails? I'm hesitant to just dump to stdout b/c of how ugly some of the logs can be.

**Comment by rsevilla87** [comment]
> Can we just dump all the logs to snappy when it fails? I'm hesitant to just dump to stdout b/c of how ugly some of the logs can be.

Are you sure we want that?, I'm aware that dumping those logs into stdout will likely create a messy output, however that will only happen when a benchmark fails. On the other hand, IIRC airflow had some kind of limitation in the log length, that could make the difference :)

**Comment by dry923** [comment]
Not sure whats the "optimal" answer. The other option as well is to not reap the cluster when it fails to let us debug "live"

**Comment by Harshith-umesh** [comment]
closed with this PR: https://github.com/cloud-bulldozer/e2e-benchmarking/pull/327
