### ISSUE TITLE
router-perf: deploy only the objects for the configured TERMINATIONS

### ISSUE THREAD

**Issue by qiliRedHat** [cloud-bulldozer/e2e-benchmarking#362]
Current behavior: No matter what we configured for TERMINATIONS, all 4 namespaces' objects are created. https://github.com/cloud-bulldozer/e2e-benchmarking/blob/master/workloads/router-perf-v2/http-perf.yml.tmpl

Expected: If I set TERMINATIONS to http, only namespace of http and the objects under it are created. Same for other TERMINATIONS combinations.

Why: A customer case needs to evaluate the performance while pod number increases for http request. Because currently we installs all 4 namespaces, the pod number is 4 times of the pods actually visited by mb. Workaround can be using a customized http-perf.yml.tmpl with only http, but I think it's good to have this built in.

Please kindly review this enhancement request, if it is ok, I can open a pr to do it.

**Comment by rsevilla87** [comment]
Hi @qiliRedHat , I was already aware of this issue, (however I didn't fix it yet as you noted here). This could be implemented with golang-templates included in kube-burner. I already have some WIP code to fix it, let me wrap it up it now.
