### ISSUE TITLE
Result sheet of the Network Perf tests is missing metrics

### ISSUE THREAD

**Issue by SachinNinganure-zz** [cloud-bulldozer/e2e-benchmarking#428]
The result sheet of the network performance tests coming back doesn't have the metadata and is missing some of the metrics.   Examples of missing metrics:  avg(norm_ltcy), avg(norm_ops) , max(norm_byte)

Please see this report which has missing metrics --https://docs.google.com/spreadsheets/d/1yMA1DStv6GbC0t0LZ0VOYO9rTRxi6Ym5_nGWYEk23bA/edit#gid=1690151223

**Comment by SachinNinganure** [comment]
what are labels I should use to get this issue addressed

**Comment by paigerube14** [comment]
@SachinNinganure are you able to give access to the google sheet with everyone in Red Hat and show what it looked like before and what's output now.

**Comment by SachinNinganure** [comment]
@paigerube14 https://docs.google.com/spreadsheets/d/1VqHxJE7aLoXBcOaWzaSBibVz5AvI_zeROAoCo5zPWFY/edit#gid=2073637806   this is what it looked earlier.
gave you the access at both the spreadsheets

**Comment by paigerube14** [comment]
I have started working on this but in relation to issue: https://github.com/cloud-bulldozer/e2e-benchmarking/issues/395

I think if we are able to have the same code currently in kube-burner be used for all the workloads that use benchmark-comparison (ie kube-burner, network-perf and router-perf)

This will allow each user to be able to get the data in their google sheets that they want be setting their specific touchstone-config files per run

Right now I have only tested from the utils folder directly not in the workloads themselves
https://github.com/paigerube14/e2e-benchmarking/tree/compare_combine

**Comment by jtaleric** [comment]
hey @SachinNinganure-zz This seems to be a issue not related to the benchmark-operator. feel free to reopen against e2e or the repo this issue is specific to. There is no concept of spreadsheets in benchmark-operator.

**Comment by paigerube14** [comment]
@SachinNinganure-zz you should be able to use the below going forward to get all the data you need. You should also be able to add any variables in the _aggregations_ section for anything that's missed 

COMPARISON_CONFIG="uperf-touchstone.json uperf-touchstone-norm.json"

**Comment by SachinNinganure** [comment]
Looks good
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/network-perf/284/
Thank you Paige
