### ISSUE TITLE
PodSecurity "restricted:v1.24"

### ISSUE THREAD

**Issue by wolfganghuse** [cloud-bulldozer/e2e-benchmarking#436]
Hi, when running a kube-burner benchmark against Openshift
Server Version: 4.11.0-0.nightly-2022-06-25-081133
Kubernetes Version: v1.24.0+9ddc8b1
i see a lot of errors like the following in my logs... 

`[pod/kube-burner-7af2f011-4djpd/kube-burner] W0627 17:28:30.556082       1 warnings.go:70] would violate PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "cluster-density" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "cluster-density" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "cluster-density" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "cluster-density" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")`

**Comment by rsevilla87** [comment]
Hi @wolfganghuse , this is a known issue because of the new PSS mechanism added in k8s 1.24, it doesn't affect the workload itself. I'm looking for a way to remove this ugly warning messages.

**Comment by paigerube14** [comment]
@rsevilla87 when using a 4.12 nightly client the pod-density test now fails with this error.  The cluster-density test however doesn't hit this issue (maybe because the pods are coming from a deployment?)

Kube-burner Pod Logs in benchmark-operator namespace 
```
W0826 18:24:59.956522       1 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2022-08-26 18:27:12" level=fatal msg="Authorization error creating Pod/node-density-1: pods \"node-density-1\" is forbidden: violates PodSecurity \"restricted:v1.24\": allowPrivilegeEscalation != false (container \"node-density\" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container \"node-density\" must set securityContext.capabilities.drop=[\"ALL\"]), seccompProfile (pod or container \"node-density\" must set securityContext.seccompProfile.type to \"RuntimeDefault\" or \"Localhost\")"

```
