### ISSUE TITLE
Lots of warnings reported when running max-namespaces and node-density-heavy

### ISSUE THREAD

**Issue by svetsa-rh** [cloud-bulldozer/e2e-benchmarking#505]
**Describe the bug**
While running max-namespaces and node-density-heavy, following warnings were reported (tons of them)

11-02 19:16:39.030  time="2022-11-02 23:16:38" level=info msg="Running job max-namespaces"
11-02 19:16:39.030  W1102 23:16:38.940691     626 warnings.go:70] unknown field "spec.triggers"
11-02 19:16:39.030  W1102 23:16:38.940976     626 warnings.go:70] unknown field "spec.triggers"
11-02 19:16:39.030  W1102 23:16:38.942360     626 warnings.go:70] unknown field "spec.triggers"
11-02 19:16:39.030  W1102 23:16:38.943423     626 warnings.go:70] unknown field "spec.triggers"
11-02 19:16:39.030  W1102 23:16:38.944769     626 warnings.go:70] unknown field "spec.triggers"
11-02 19:16:39.030  W1102 23:16:38.945951     626 warnings.go:70] unknown field "spec.triggers"
11-02 19:16:39.030  W1102 23:16:38.948107     626 warnings.go:70] unknown field "spec.portalIP"
11-02 19:16:39.030  W1102 23:16:39.008207     626 warnings.go:70] unknown field "spec.triggers"
11-02 19:16:39.030  W1102 23:16:39.013833     626 warnings.go:70] unknown field "spec.portalIP"
11-02 19:16:39.284  W1102 23:16:39.033571     626 warnings.go:70] unknown field "spec.triggers"

See 
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/kube-burner/1583/consoleFull
and
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/kube-burner/1587/console

**To Reproduce**
Execute max-namespaces and/or node-density-heavy test on a 4.12 nightly build. 

Client Version: 4.12.0-0.nightly-2022-10-05-053337
Kustomize Version: v4.5.4
Server Version: 4.12.0-0.nightly-arm64-2022-11-02-075603
Kubernetes Version: v1.25.2+1f53707

**Expected behavior**
No warnings should be reported.

**Screenshots**

**Additional context**

**Comment by svetsa-rh** [comment]
Some additional info from a related QE jira https://issues.redhat.com/browse/OCPQE-12469 by @paigerube14 

> PortalIP is an easy removal because it's not set to anything in this file: https://github.com/cloud-bulldozer/e2e-benchmarking/blob/master/workloads/kube-burner/workloads/node-density-heavy/postgres-service.yml

spec.triggers is a little more confusing because it is set to a value, need to investigate more why this maybe was removed in a deployment. Key is in both files below

https://github.com/cloud-bulldozer/e2e-benchmarking/blob/master/workloads/kube-burner/workloads/node-density-heavy/app-deployment.yml
https://github.com/cloud-bulldozer/e2e-benchmarking/blob/master/workloads/kube-burner/workloads/node-density-heavy/postgres-deployment.yml

**Comment by svetsa-rh** [comment]
Undesired result of this issue https://issues.redhat.com/browse/OCPQE-12730

**Comment by afcollins** [comment]
Seems straightforward.

portalIP was renamed to "clusterIP" in 2015 (kubernetes PR #8740)

Pretty sure that 'triggers' was only ever on the (openshift-specific) DeploymentConfig object. They can (and should) be removed throughout when we are using (upstream k8s) Deployment.

**Comment by paigerube14** [comment]
Related issue fix in docs: https://github.com/openshift/openshift-docs/pull/52638

**Comment by rsevilla87** [comment]
Fixed in #508
