### ISSUE TITLE
Etcd-perf test needs to run on the master nodes

### ISSUE THREAD

**Issue by chaitanyaenr** [cloud-bulldozer/e2e-benchmarking#56]
Etcd-perf test runs fio to capture the latency/fsync metrics on the disk. Currently, the pod gets scheduled on one of the worker nodes and they might not be using the same disk as master nodes, we need to make sure the test pod is scheduled on one of the master nodes to be able to hit the location used by the etcd to read/write.

**Comment by whitleykeith** [comment]
I think this issue needs to still be opened. While the operator can support adding node selectors to the etcd perf test now, the script itself doesn't set that yet.
