### ISSUE TITLE
kube-burner workload node-density-cni-networkpolicy: unable to render template

### ISSUE THREAD

**Issue by sjug** [cloud-bulldozer/e2e-benchmarking#565]
**Describe the bug**
The kube-burner workload `node-density-cni-networkpolicy` template is not able to be rendered.

**To Reproduce**
1. Run workload `WORKLOAD=node-density-cni-networkpolicy`
2. See error below.

**Actual behavior**
```
###############################################
Workload: node-density-cni-networkpolicy
Workload template: workloads/node-density-cni-networkpolicy/node-density-cni-networkpolicy.yml
Metrics profile: metrics-profiles/metrics.yaml
Alerts profile:
QPS: 10
Burst: 10
UUID: 122a406e-baf6-4dde-9b42-0d20be567c7d
Node count: 1
Pods per node: 245
###############################################
Mon May 15 04:21:45 PM UTC 2023 Indexing enabled, using metrics from metrics-profiles/metrics.yaml
~/Work/e2e-benchmarking/workloads/kube-burner/workloads/node-density-cni-networkpolicy ~/Work/e2e-benchmarking/workloads/kube-burner
INFO[2023-05-15 12:21:45] 🔥 Starting kube-burner (0.17.3@c38fe7eb37c62686b68e2b64bdc8311a4d73d8f1) with UUID 122a406e-baf6-4dde-9b42-0d20be567c7d
**FATA[2023-05-15 12:21:45] Error rendering configuration template: parsing error: template: :96: unexpected "}" in operand
~/Work/e2e-benchmarking/workloads/kube-burner**
Mon May 15 04:21:45 PM UTC 2023 Indexing benchmark metadata to https://URL:443/ripsaw-kube-burner
Mon May 15 04:21:46 PM UTC 2023 benchmark
```

**Expected behavior**
I expect the template to render and for kube-burner to execute the workload.

**Comment by jtaleric** [comment]
https://github.com/cloud-bulldozer/e2e-benchmarking/blob/master/workloads/kube-bur[…]de-density-cni-networkpolicy/node-density-cni-networkpolicy.yml 

Line 96 and 107 are missing ending `}`

`nodeSelector: "{{.POD_NODE_SELECTOR}"` should be `nodeSelector: "{{.POD_NODE_SELECTOR}}"` 

Could you test this change locally and let us know if that fixes this problem?

**Comment by sjug** [comment]
Works, it's like magic!

**Comment by jtaleric** [comment]
Oh this is still a bug :)

**Comment by sjug** [comment]
Sorry probably pre-emptive close.

**Comment by sjug** [comment]
There's also new warnings getting emitted, I'm thinking the node-density-cni had this resolved?
```
W0515 13:08:04.934510   84040 warnings.go:70] would violate PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "curlapp" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "curlapp" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "curlapp" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "curlapp" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```

**Comment by rsevilla87** [comment]
> There's also new warnings getting emitted, I'm thinking the node-density-cni had this resolved?
> 
> ```
> W0515 13:08:04.934510   84040 warnings.go:70] would violate PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "curlapp" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "curlapp" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "curlapp" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "curlapp" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
> ```

Should be fixed by https://github.com/cloud-bulldozer/kube-burner/pull/320, have to cut a new release though
