### ISSUE TITLE
CI pipeline

### ISSUE THREAD

**Issue by rsevilla87** [cloud-bulldozer/e2e-benchmarking#60]
We need a CI since these scripts are becoming more critical.

**Comment by whitleykeith** [comment]
Jsst a few questions

How do we consume these scripts? Do teams cherry pick these when they want to run them in their own CI, are they part of the larger builds etc.

If we're targeting these for consumption, we should think through how we would want to surface the core logic. What do we want the artifact to look like? How do we handle the large amount of parameters that need to be set currently? Do we care about surfacing these up to a more general audience, say general Kubernetes clusters?

**Comment by jtaleric** [comment]
> Just a few questions
> 
> How do we consume these scripts? Do teams cherry pick these when they want to run them in their own CI, are they part of the larger builds etc.
> 
> If we're targeting these for consumption, we should think through how we would want to surface the core logic. What do we want the artifact to look like? How do we handle the large amount of parameters that need to be set currently? Do we care about surfacing these up to a more general audience, say general Kubernetes clusters?

Ah, just saw this, so let me address this question... 

> How do we consume these scripts?

Today, we consume these scripts in our Performance CI - we define the environmental vars and call the specific e2e-benchmarking workload. 

We would like to eventually have other teams use/contribute....

**Comment by rsevilla87** [comment]
Fixed by #114
