### ISSUE TITLE
Kube burner install latest inconsistent/failing 

### ISSUE THREAD

**Issue by paigerube14** [cloud-bulldozer/e2e-benchmarking#619]
**Describe the bug**
Kube burner randomly is not able to get the latest kube-burner version. Would be good to either have a backup version or retry the curl command 2 or 3 times to try to get around this. And if it still fails, throw a better error 

```
08-28 11:05:00.106  + ./run.sh
08-28 11:05:00.106  + tee kube-burner-ocp.out
08-28 11:05:00.106  jq: error (at <stdin>:1): Cannot iterate over null (null)
```

**To Reproduce**
1. Checkout e2e-benchmark
2. cd workloads/kube-burner-ocp-wrapper
3. /run.sh

**Expected behavior**
The workload runs as expected and no error is thrown

**Screenshots**
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/kube-burner-ocp/186/console

**Additional context**

CC: @nathan-weinberg

**Comment by paigerube14** [comment]
Are we also able to install jq as a requirement with e2e-benchmarking by default. I had to add pip installs into our jenkins jobs to get around this because the system might not have it by default

**Comment by paigerube14** [comment]
I've hit this issue off and on many times (don't have exact record) but spitting out a better error message and retrying 2 or 3 times with a small wait inbetween would be very helpful

**Comment by qiliRedHat** [comment]
I met this issue several times yesterday. Example:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/kube-burner-ocp/230/console

**Comment by svetsa-rh** [comment]
another one https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/kube-burner-ocp/240/console

**Comment by vishnuchalla** [comment]
looks like there is some delay/error in [curl](https://github.com/cloud-bulldozer/e2e-benchmarking/blob/master/workloads/kube-burner-ocp-wrapper/run.sh#L19) command execution (for fetching latest tagged assets) in jenkins test setup. I would recommend to use `KUBE_BURNER_VERSION` by specifying the desired version of kube-burner to be executed (for example v1.7.6 or so) in the job params for OCP runs like we are using `KUBE_BURNER_URL` var for non-ocps runs [here](https://github.com/openshift-qe/ocp-qe-perfscale-ci/blob/kube-burner/Jenkinsfile#L84). This will help us have stable and consistent runs

**Comment by rsevilla87** [comment]
Can we close this issue @paigerube14 ?

**Comment by paigerube14** [comment]
Yes!
