### ISSUE TITLE
feature: define standardized workloads based on node count

### ISSUE THREAD

**Issue by hexfusion** [cloud-bulldozer/e2e-benchmarking#73]
OpenShift needs a standardized tool that can be used to synthesize actual workloads for the cluster based on the node count.

So for example I would expect something like this as the user experience.

./benchmark --workers 3

This would run what OCP considers as the high end of a workload for 3 nodes. From this workload, the expectation is given the hardware requirements for the cluster are met that the test will pass. If the test fails the cluster-admin should be able to go to the console and review the alerts on the cluster. Those alerts should provide direct direction to admin of resolution steps to resolve performance alerts.

IE disks too slow ..

**Comment by hexfusion** [comment]
cc @jtaleric

**Comment by jtaleric** [comment]
😢
