### ISSUE TITLE
JOB_TIMEOUT is not used in the kube-burner e2e tests

### ISSUE THREAD

**Issue by dry923** [cloud-bulldozer/e2e-benchmarking#86]
The wait_for_benchmark function in the kube-burner common.sh does not have any timeout so it could run forever. We have an environment variable that gets set at the top of the file (JOB_TIMEOUT) but do not ever use it in the script.

**Comment by dry923** [comment]
CC: @rsevilla87 @chaitanyaenr

**Comment by rsevilla87** [comment]
@dry923, JOB_TIMEOUT is actually used as timeout of the kubernetes job.

https://github.com/cloud-bulldozer/e2e-benchmarking/blob/master/workloads/kube-burner/kube-burner-crd.yaml#L31

However, as you mentioned, we should make use of this variable in the overall script as well to avoid getting stuck in case of failure in a previous phase, will fix that ;)
